# Generated by Django 4.1.1 on 2022-09-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0002_alter_taskmanager_progress_delete_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='taskmanager',
            name='modify_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
